# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PyAmpTools
author: Lawrence Ng
copyright: '2025'

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.autosummary"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
  config:
    add_module_names: False

autosummary_generate: True
autosummary_imported_members: True

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 2000
  # exclude_patterns:
    # - demos/analysis_chain.ipynb

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
    title: PyAmpTools
    author: Lawrence Ng
    documentclass: book

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/lan13005/PyAmpTools # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true